remote_theme: "owasp/www--site-theme@main"
permalink: :path
#override default star and watch buttons
code_user: OWASP
code_repo: wstg
# core files/folders to exclude
exclude:
    - README.md
plugins:
    - jekyll-include-cache-0.2.0
stable_version: v42
