name: Validate OWASP entity metadata

on:
  pull_request:
    paths:
      - '*.owasp.yaml'
  push:
    paths:
      - '*.owasp.yaml'

permissions:
  contents: read

concurrency:
  cancel-in-progress: true
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}

jobs:
  validate-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Validate metadata file
        uses: owasp/nest-schema/.github/actions/validate@7e55a04dce2fea3606abdf49e9cb8e7f465ab801
