name: Validate OWASP entity metadata

on:
  pull_request:
    paths:
      - '*.owasp.yaml'
  push:
    paths:
      - '*.owasp.yaml'

permissions:
  contents: read

concurrency:
  cancel-in-progress: true
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}

jobs:
  validate-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Validate metadata file
        uses: owasp/nest-schema/.github/actions/validate@8ab4b92539f4cfe1cb868836fd6d2b93ea21bd35
